/* Security.vcl breach2vcl config VCL
 * Copyright (C) 2009 Kacper Wysocki
 * 
 * the rules enabled here are auto-generated by ../tools/all2vcl.pl
 */

include "breach/20_protocol_violations.vcl";
include "breach/21_protocol_anomalies.vcl";
include "breach/23_request_limits.vcl";
include "breach/30_http_policy.vcl";
include "breach/35_bad_robots.vcl";
include "breach/40_generic_attacks.vcl";
include "breach/45_trojans.vcl";
include "breach/50_outbound.vcl";
